UNSOLVED-WA/unsolved-back-end

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

issue template를 통해 원활한 issue 활용을 위해
issue template 추가

Docs: Add issue template

---

.github/workflows/docker.yml

배포 자동화를 위한 dockerize와 docker hub 배포
main에 merge 되었을경우 docekr hub에 image를 만들어 publish 하도록 action workflow 생성
release, tag 자동 생성 workflow 도 구축하여 도입 예정

Feat: Add publish docker

---

README.md

readme 파일로 프로젝트에 대한 설명
readme 파일 작성
- introduce 작성
- branch 규칙 작성
- pr convention 작성
- commit convention 작성
양식 출처 : https://github.com/innovationacademy-kr/42Swim

📝 docs : write readme.md

---

build.gradle

#7 
lombok, mysql, JPA gradle dependency에 추가

Chore: dependency add library gradle

---

src/main/java/com/unsolvedwa/unsolvedwa/BaseTimeEntity.java
src/main/java/com/unsolvedwa/unsolvedwa/BaserTimeEntity.java
src/main/java/com/unsolvedwa/unsolvedwa/problem/Problem.java
src/main/java/com/unsolvedwa/unsolvedwa/ranking/Ranking.java
src/main/java/com/unsolvedwa/unsolvedwa/user/User.java

#8 
problem, ranking, user entity 추가
공통사항은 BasetimeEntity 추상클래스 생성, 상속처리했습니다.

Feature: add entity

---

src/main/java/com/unsolvedwa/unsolvedwa/BaseTimeEntity.java
src/main/java/com/unsolvedwa/unsolvedwa/group/Group.java
src/main/java/com/unsolvedwa/unsolvedwa/group/ProblemGroup.java
src/main/java/com/unsolvedwa/unsolvedwa/group/UserGroup.java
src/main/java/com/unsolvedwa/unsolvedwa/problem/Problem.java
src/main/java/com/unsolvedwa/unsolvedwa/ranking/Ranking.java
src/main/java/com/unsolvedwa/unsolvedwa/user/User.java

특정 조직뿐만이 아닌 모든 조직을 위한 서비스를 위한 DB구조 수정에 따른 entity 수정
- BaseTimeEntity의 createAt update 불가 및 Nullable 불가
- group, problem_group, user_group entity 추가
- 기존 entity의 이동된 속성 삭제

Feature: 추가 entity 및 기존 entity 수정

---

src/main/java/com/unsolvedwa/unsolvedwa/problem/ProblemController.java
src/main/java/com/unsolvedwa/unsolvedwa/problem/ProblemRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/problem/ProblemService.java
src/main/java/com/unsolvedwa/unsolvedwa/user/UserController.java
src/main/java/com/unsolvedwa/unsolvedwa/user/UserRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/user/UserService.java

#9 #10 
UserRepoistory, UserService, UserController 작성
기본 함수로 GET /{domain] 형태의 api까지 추가

Feature: user domain

---

src/main/java/com/unsolvedwa/unsolvedwa/team/UserTeam.java
src/main/java/com/unsolvedwa/unsolvedwa/user/User.java

#29 
user.score 삭제하고 user_team.score 추가

Feature: user entity modify

---

src/main/java/com/unsolvedwa/unsolvedwa/problem/ProblemRepositoryImpl.java

Fix: wrong import

---

src/main/java/com/unsolvedwa/unsolvedwa/UnsolvedWaApplication.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/TeamRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/user/UserRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/userteam/UserTeamRepository.java

api 구현하기 위해 사용할 repository 의 find 메서드들 필요함
jpa repository 를 이용하여 find 메서드 구현

Feature : jpa repository find method

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/UserController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/user/UserRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/user/UserService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/user/dto/UserResDTO.java

#39 
유저 프로필 페이지를 위한 api
유저의 bojId를 통해 유저의 정보를 조회하는 api 작성

🎉 Feat: getUserProfileByBojId api

---

.github/workflows/gradle.yml
.github/workflows/test.yml

gradle로 build를 테스트 하고 있었으나 db를 연결하기 위해
db container를 띄우기 위해 docker compose 로 build하도록 수정

Chore: docker compose로 build하도록 수정

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/RankingController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/dto/MonthRankingResponseDto.java
src/test/java/com/unsolvedwa/unsolvedwa/controller/RankingControllerTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingServiceTest.java

#50 
월간랭킹 상위 10명 조회에서 전체 조회로 수정

Feature : month all ranking

---

.github/workflows/auto-label.yml

issue에 할당되어있는 label을 자동으로 pr에도 할당

💚 ci: auto label in issue

---

src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/ProblemResponseDto.java

- problem api 구현 위해 problem resposen dto 작성
- problem resposen dto 작성

Feature : dto

---

README.md

Docs : readme-usage

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/ProblemController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/Problem.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/ProblemResponseDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/SolvingProblemResponseDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/Team.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/TeamRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/TeamRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/userteam/UserTeamRepository.java
src/test/java/com/unsolvedwa/unsolvedwa/controller/ProblemControllerTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemRepositoryTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemServiceTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryTest.java
src/test/resources/application.yaml

Feature : unsolved-tier

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/RankingController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/dto/AllRankingResponseDto.java
src/main/resources/application.yaml
src/test/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryTest.java

Feature: allranking

---

build.gradle
src/main/java/com/unsolvedwa/unsolvedwa/controller/ProblemController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/SolvingProblemRequestDto.java
src/test/java/com/unsolvedwa/unsolvedwa/controller/ProblemControllerTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemServiceTest.java

#41 
- 문제 풀었을때 사용하는 api 구현
- 테스트 코드 작성

Feature : solve problem

---

.github/workflows/distribute.yml

ci: add distribute workflow

---

.github/workflows/distribute.yml

💚 ci: docker-compose distribute

---

Dockerfile
docker-compose.yml
src/main/resources/application.yaml

- mysql dialect 에러로 테이블이 생성되지 않음
- dialect 변경
- dockerfile 수정
- docker-compose 수정

Bugfix : change mysql dialect 

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/RankingController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/Ranking.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/dto/MonthRankingHistoryResponseDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/ranking/dto/MonthRankingResponseDto.java
src/test/java/com/unsolvedwa/unsolvedwa/controller/RankingControllerTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingRepositoryTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/ranking/RankingServiceTest.java

- 특정 유저, 특정 팀 랭킹 기록 api 구현
- 특정 유저, 특정 팀 랭킹 기록 api 구현
- 테스트 코드 작성

Feature : ranking history

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/ProblemController.java

#69 
- api url 변경
- api swagger 설명 수정

Feature : api url

---

.github/workflows/auto-label.yml
src/main/java/com/unsolvedwa/unsolvedwa/controller/ProblemController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/SolvingProblemRequestDto.java
src/test/java/com/unsolvedwa/unsolvedwa/controller/ProblemControllerTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemRepositoryTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemServiceTest.java

#72 
- solving request dto 수정
- solving controller, service 수정
- solving test code 수정

Feature : solving request

---

src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/ProblemResponseDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/SolvingProblemResponseDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepositoryImpl.java
src/test/java/com/unsolvedwa/unsolvedwa/controller/ProblemControllerTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemServiceTest.java

- unsolved 문제 가져오는 response에 백준 문제 번호 정보가 없음
- unsolved api의 response에 problemNumber 추가
- unsolved api의 response에 problemNumber 추가에 따른 코드 수정

Feature : unsolved response

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/ProblemController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/Team.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/TeamRepository.java
src/test/java/com/unsolvedwa/unsolvedwa/controller/ProblemControllerTest.java
src/test/java/com/unsolvedwa/unsolvedwa/domain/problem/ProblemServiceTest.java

#79 
- unsolved api 에서 teamName 대신 teamId 받도록 변경
- 테스트 코드에 변경 사항 적용
- 테스트 코드를 위해 Team 에 setIdForTest 메서드 추가

Feature : team request dto

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/TeamController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/TeamRepository.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/TeamService.java

#82 
- team name 으로 team 조회 api 구현

Feature : find team by name

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/ProblemController.java
src/main/java/com/unsolvedwa/unsolvedwa/controller/TeamController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/ProblemResponseDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/team/dto/TeamResponseDto.java

#75 
- responseDto에 entity 생성자 추가
- entity를 response 하는 api 를 dto를 response 하도록 변경

Bugfix : entity to response entity

---

src/main/java/com/unsolvedwa/unsolvedwa/controller/UserController.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problem/dto/SolvedProblemRequestDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepositoryCustom.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamRepositoryImpl.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/problemteam/ProblemTeamService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/user/UserService.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/user/dto/UserReqestDto.java
src/main/java/com/unsolvedwa/unsolvedwa/domain/user/dto/UserResDTO.java

Feature: create user
